Update suggestion
Dragon1573/winget-pkgs pull request #5
Opened 2024-11-30 13:18 UTC by DuckDuckStudio

Description:

- I don't think the `ElevationRequirement` should be added. (This was also not be added in the previous version), so I removed it.
( More: [In version 1.3](https://github.com/microsoft/winget-pkgs/pull/173045#issuecomment-2347086572) )

- ~~This package is **available on x64,x86,arm, and arm64**, and I added them.~~ (Resolved)

- I updated the **tags** in the Chinese (zh-CN) manifest.

- I didn't add `ProductCode` to [the iss file for this package](https://github.com/DuckDuckStudio/GitHub-Labels-Manager/blob/main/pack.iss) , so I removed the `ProductCode` from the manifest.

- ~~I have a _question_ , does winget automatically find the appropriate silent install switch when the manifest is not explicitly specified?~~ (Resolved)

- The License is **GNU General Public License v3.0** . No more. (软著登记号是之前版本的，没审核这么快)

- I added the `ReleaseNotes` for this version.

> [!WARNING]
> In previous versions, the version number was preceded by a "v", but this version does not. Does this cause Update-Always-Available?

2024-11-30 13:48 UTC, DuckDuckStudio commented on manifests/d/DuckStudio/GitHubLabelsManager/1.5/DuckStudio.GitHubLabelsManager.yaml
> +PackageVersion: 1.5
```suggestion
PackageVersion: '1.5'
```

2024-11-30 13:50 UTC, DuckDuckStudio commented
Changes done.

2024-11-30 16:53 UTC, Dragon1573 requested changes
I previously create the manifest with a brand new package identifier accidentally, everything were inspected by _Komac_, including `ElevationRequirement`, `ProductCode` and `AppsAndFeaturesEntries`.

2024-11-30 16:53 UTC, Dragon1573 commented on manifests/d/DuckStudio/GitHubLabelsManager/1.5/DuckStudio.GitHubLabelsManager.locale.en-US.yaml
> +ReleaseNotesUrl: https://github.com/DuckDuckStudio/Chinese_git/releases/tag/v1.5
```suggestion
ReleaseNotesUrl: https://github.com/DuckDuckStudio/GitHub-Labels-Manager/releases/tag/v1.5
```

Is it another "accident"? 😄

2024-12-01 01:04 UTC, DuckDuckStudio commented on manifests/d/DuckStudio/GitHubLabelsManager/1.5/DuckStudio.GitHubLabelsManager.locale.en-US.yaml
> +ReleaseNotesUrl: https://github.com/DuckDuckStudio/Chinese_git/releases/tag/v1.5
Thank you for catching this issue!

2024-12-01 05:12 UTC, Dragon1573 commented
> [!CAUTION]
>
> Unwanted commits are included in the pull requests!
>
> Since fixing them are too complicated. This pull request will be rejected 😞

> [!NOTE]
>
> The related pull request microsoft#195394 will also be closed. I'll try to recreate a new pull request of this package.

2024-12-01 05:12 UTC, closed without merging